table BaseDados
	lineageTag: 946e0897-6d36-4be3-811c-09c7d18d189c

	column 'Nome da Origem'
		dataType: string
		lineageTag: 428102b4-5b2f-414d-9165-4f0d7e8cd217
		summarizeBy: none
		sourceColumn: Nome da Origem

		annotation SummarizationSetBy = Automatic

	column 'Matricula '
		dataType: int64
		formatString: 0
		lineageTag: 71c8d47e-13a0-4980-94f5-55665ec6ad8d
		summarizeBy: sum
		sourceColumn: "Matricula "

		annotation SummarizationSetBy = Automatic

	column ' Cargo '
		dataType: string
		lineageTag: 1db4e964-3b19-40f8-9e5e-043fe44f3446
		summarizeBy: none
		sourceColumn: " Cargo "

		annotation SummarizationSetBy = Automatic

	column ' Mês Pag. '
		dataType: dateTime
		formatString: Long Date
		lineageTag: 69a70d9a-e780-44a7-8c47-9075b0af6482
		summarizeBy: none
		sourceColumn: " Mês Pag. "

		variation Variation
			isDefault
			relationship: b00230a3-2392-4ff2-990a-06d115eecb08
			defaultHierarchy: LocalDateTable_99a3733a-f6c9-406a-9169-6c4c9bf1383f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ' Evento '
		dataType: int64
		formatString: 0
		lineageTag: 6a49ae8f-2b1d-4e26-b5d1-5ed46f00b454
		summarizeBy: sum
		sourceColumn: " Evento "

		annotation SummarizationSetBy = Automatic

	column ' Descrição '
		dataType: string
		lineageTag: 40f4e068-d379-4cec-82e4-863b55d9ab55
		summarizeBy: none
		sourceColumn: " Descrição "

		annotation SummarizationSetBy = Automatic

	column ' Tipo '
		dataType: string
		lineageTag: cfc89829-57b8-48a0-a629-c5a16d3caa3a
		summarizeBy: none
		sourceColumn: " Tipo "

		annotation SummarizationSetBy = Automatic

	column ' Valor'
		dataType: double
		lineageTag: 5ae15dad-06c1-4bd9-8f42-f29422bf4dcf
		summarizeBy: sum
		sourceColumn: " Valor"

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition BaseDados = m
		mode: import
		source =
				let
				    Fonte = Folder.Files("C:\Users\lucas\OneDrive\Área de Trabalho\Analise_dados_google_MD\Projeto_People_Analytics\BaseDados"),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(Fonte, each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo", each #"Transformar Arquivo"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo", Table.ColumnNames(#"Transformar Arquivo"(#"Arquivo de Amostra"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"Matricula ", Int64.Type}, {" Cargo ", type text}, {" Mês Pag. ", type date}, {" Evento ", Int64.Type}, {" Descrição ", type text}, {" Tipo ", type text}, {" Valor", type number}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([Nome da Origem] <> "Funcionarios.xlsx"))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

