table Calendario
	lineageTag: d4e5f601-0000-4a00-9000-000000000000

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4e5f601-0000-4a00-9000-000000000001
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: d4e5f601-0000-4a00-9000-000000000002
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = User

	column 'Mês Número'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d4e5f601-0000-4a00-9000-000000000003
		summarizeBy: none
		sourceColumn: Mês Número

		annotation SummarizationSetBy = User

	column Mês
		dataType: string
		lineageTag: d4e5f601-0000-4a00-9000-000000000004
		summarizeBy: none
		sourceColumn: Mês
		sortByColumn: 'Mês Número'

		annotation SummarizationSetBy = User

	column Ano-Mês
		dataType: string
		lineageTag: d4e5f601-0000-4a00-9000-000000000005
		summarizeBy: none
		sourceColumn: Ano-Mês

		annotation SummarizationSetBy = User

	column Trimestre
		dataType: string
		lineageTag: d4e5f601-0000-4a00-9000-000000000006
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = User

	column Ano-Trimestre
		dataType: string
		lineageTag: d4e5f601-0000-4a00-9000-000000000007
		summarizeBy: none
		sourceColumn: Ano-Trimestre

		annotation SummarizationSetBy = User

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: d4e5f601-0000-4a00-9000-000000000008
		summarizeBy: none
		sourceColumn: Dia

		annotation SummarizationSetBy = User

	column 'Dia Semana Número'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d4e5f601-0000-4a00-9000-000000000009
		summarizeBy: none
		sourceColumn: Dia Semana Número

		annotation SummarizationSetBy = User

	column 'Dia da Semana'
		dataType: string
		lineageTag: d4e5f601-0000-4a00-9000-000000000010
		summarizeBy: none
		sourceColumn: Dia da Semana
		sortByColumn: 'Dia Semana Número'

		annotation SummarizationSetBy = User

	column 'Fim de Semana'
		dataType: boolean
		lineageTag: d4e5f601-0000-4a00-9000-000000000011
		summarizeBy: none
		sourceColumn: Fim de Semana

		annotation SummarizationSetBy = User

	column 'Início do Mês'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4e5f601-0000-4a00-9000-000000000012
		summarizeBy: none
		sourceColumn: Início do Mês

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column 'Fim do Mês'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d4e5f601-0000-4a00-9000-000000000013
		summarizeBy: none
		sourceColumn: Fim do Mês

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

	column 'Semana do Ano'
		dataType: int64
		formatString: 0
		lineageTag: d4e5f601-0000-4a00-9000-000000000014
		summarizeBy: none
		sourceColumn: Semana do Ano

		annotation SummarizationSetBy = User

	column 'Dia do Ano'
		dataType: int64
		formatString: 0
		lineageTag: d4e5f601-0000-4a00-9000-000000000015
		summarizeBy: none
		sourceColumn: Dia do Ano

		annotation SummarizationSetBy = User

	column 'É Feriado'
		dataType: boolean
		lineageTag: d4e5f601-0000-4a00-9000-000000000016
		summarizeBy: none
		sourceColumn: É Feriado

		annotation SummarizationSetBy = User

	column 'Nome Feriado'
		dataType: string
		lineageTag: d4e5f601-0000-4a00-9000-000000000017
		summarizeBy: none
		sourceColumn: Nome Feriado

		annotation SummarizationSetBy = User

	hierarchy 'Hierarquia de Datas'
		lineageTag: d4e5f601-0000-4a00-9000-000000000018

		level Ano
			lineageTag: d4e5f601-0000-4a00-9000-000000000019
			column: Ano

		level Trimestre
			lineageTag: d4e5f601-0000-4a00-9000-000000000020
			column: Trimestre

		level Mês
			lineageTag: d4e5f601-0000-4a00-9000-000000000021
			column: Mês

		level Dia
			lineageTag: d4e5f601-0000-4a00-9000-000000000022
			column: Dia

	partition Calendario = m
		mode: import
		source =
				let
				    DataInicio = #date(2002,1,1),
				    DataFim = #date(2020,12,31),
				    NumDias = Duration.Days(DataFim - DataInicio) + 1,
				    Datas = List.Dates(DataInicio, NumDias, #duration(1,0,0,0)),
				    #"Convertido para Tabela" = Table.FromList(Datas, Splitter.SplitByNothing(), {"Date"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela", {{"Date", type date}}),
				
				    Feriados = Table.FromRecords({
				    [Data = #date(2002,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2002,2,11), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2002,2,12), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2002,3,29), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2002,3,31), Feriado = "Páscoa"],
				    [Data = #date(2002,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2002,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2002,5,30), Feriado = "Corpus Christi"],
				    [Data = #date(2002,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2002,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2002,11,2), Feriado = "Finados"],
				    [Data = #date(2002,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2002,12,25), Feriado = "Natal"],
				    [Data = #date(2003,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2003,3,3), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2003,3,4), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2003,4,18), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2003,4,20), Feriado = "Páscoa"],
				    [Data = #date(2003,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2003,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2003,6,19), Feriado = "Corpus Christi"],
				    [Data = #date(2003,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2003,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2003,11,2), Feriado = "Finados"],
				    [Data = #date(2003,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2003,12,25), Feriado = "Natal"],
				    [Data = #date(2004,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2004,2,23), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2004,2,24), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2004,4,9), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2004,4,11), Feriado = "Páscoa"],
				    [Data = #date(2004,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2004,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2004,6,10), Feriado = "Corpus Christi"],
				    [Data = #date(2004,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2004,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2004,11,2), Feriado = "Finados"],
				    [Data = #date(2004,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2004,12,25), Feriado = "Natal"],
				    [Data = #date(2005,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2005,2,7), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2005,2,8), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2005,3,25), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2005,3,27), Feriado = "Páscoa"],
				    [Data = #date(2005,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2005,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2005,5,26), Feriado = "Corpus Christi"],
				    [Data = #date(2005,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2005,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2005,11,2), Feriado = "Finados"],
				    [Data = #date(2005,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2005,12,25), Feriado = "Natal"],
				    [Data = #date(2006,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2006,2,27), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2006,2,28), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2006,4,14), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2006,4,16), Feriado = "Páscoa"],
				    [Data = #date(2006,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2006,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2006,6,15), Feriado = "Corpus Christi"],
				    [Data = #date(2006,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2006,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2006,11,2), Feriado = "Finados"],
				    [Data = #date(2006,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2006,12,25), Feriado = "Natal"],
				    [Data = #date(2007,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2007,2,19), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2007,2,20), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2007,4,6), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2007,4,8), Feriado = "Páscoa"],
				    [Data = #date(2007,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2007,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2007,6,7), Feriado = "Corpus Christi"],
				    [Data = #date(2007,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2007,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2007,11,2), Feriado = "Finados"],
				    [Data = #date(2007,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2007,12,25), Feriado = "Natal"],
				    [Data = #date(2008,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2008,2,4), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2008,2,5), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2008,3,21), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2008,3,23), Feriado = "Páscoa"],
				    [Data = #date(2008,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2008,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2008,5,22), Feriado = "Corpus Christi"],
				    [Data = #date(2008,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2008,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2008,11,2), Feriado = "Finados"],
				    [Data = #date(2008,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2008,12,25), Feriado = "Natal"],
				    [Data = #date(2009,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2009,2,23), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2009,2,24), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2009,4,10), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2009,4,12), Feriado = "Páscoa"],
				    [Data = #date(2009,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2009,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2009,6,11), Feriado = "Corpus Christi"],
				    [Data = #date(2009,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2009,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2009,11,2), Feriado = "Finados"],
				    [Data = #date(2009,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2009,12,25), Feriado = "Natal"],
				    [Data = #date(2010,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2010,2,15), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2010,2,16), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2010,4,2), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2010,4,4), Feriado = "Páscoa"],
				    [Data = #date(2010,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2010,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2010,6,3), Feriado = "Corpus Christi"],
				    [Data = #date(2010,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2010,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2010,11,2), Feriado = "Finados"],
				    [Data = #date(2010,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2010,12,25), Feriado = "Natal"],
				    [Data = #date(2011,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2011,3,7), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2011,3,8), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2011,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2011,4,22), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2011,4,24), Feriado = "Páscoa"],
				    [Data = #date(2011,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2011,6,23), Feriado = "Corpus Christi"],
				    [Data = #date(2011,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2011,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2011,11,2), Feriado = "Finados"],
				    [Data = #date(2011,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2011,12,25), Feriado = "Natal"],
				    [Data = #date(2012,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2012,2,20), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2012,2,21), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2012,4,6), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2012,4,8), Feriado = "Páscoa"],
				    [Data = #date(2012,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2012,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2012,6,7), Feriado = "Corpus Christi"],
				    [Data = #date(2012,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2012,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2012,11,2), Feriado = "Finados"],
				    [Data = #date(2012,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2012,12,25), Feriado = "Natal"],
				    [Data = #date(2013,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2013,2,11), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2013,2,12), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2013,3,29), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2013,3,31), Feriado = "Páscoa"],
				    [Data = #date(2013,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2013,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2013,5,30), Feriado = "Corpus Christi"],
				    [Data = #date(2013,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2013,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2013,11,2), Feriado = "Finados"],
				    [Data = #date(2013,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2013,12,25), Feriado = "Natal"],
				    [Data = #date(2014,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2014,3,3), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2014,3,4), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2014,4,18), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2014,4,20), Feriado = "Páscoa"],
				    [Data = #date(2014,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2014,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2014,6,19), Feriado = "Corpus Christi"],
				    [Data = #date(2014,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2014,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2014,11,2), Feriado = "Finados"],
				    [Data = #date(2014,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2014,12,25), Feriado = "Natal"],
				    [Data = #date(2015,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2015,2,16), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2015,2,17), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2015,4,3), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2015,4,5), Feriado = "Páscoa"],
				    [Data = #date(2015,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2015,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2015,6,4), Feriado = "Corpus Christi"],
				    [Data = #date(2015,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2015,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2015,11,2), Feriado = "Finados"],
				    [Data = #date(2015,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2015,12,25), Feriado = "Natal"],
				    [Data = #date(2016,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2016,2,8), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2016,2,9), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2016,3,25), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2016,3,27), Feriado = "Páscoa"],
				    [Data = #date(2016,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2016,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2016,5,26), Feriado = "Corpus Christi"],
				    [Data = #date(2016,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2016,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2016,11,2), Feriado = "Finados"],
				    [Data = #date(2016,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2016,12,25), Feriado = "Natal"],
				    [Data = #date(2017,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2017,2,27), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2017,2,28), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2017,4,14), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2017,4,16), Feriado = "Páscoa"],
				    [Data = #date(2017,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2017,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2017,6,15), Feriado = "Corpus Christi"],
				    [Data = #date(2017,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2017,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2017,11,2), Feriado = "Finados"],
				    [Data = #date(2017,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2017,12,25), Feriado = "Natal"],
				    [Data = #date(2018,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2018,2,12), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2018,2,13), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2018,3,30), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2018,4,1), Feriado = "Páscoa"],
				    [Data = #date(2018,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2018,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2018,5,31), Feriado = "Corpus Christi"],
				    [Data = #date(2018,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2018,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2018,11,2), Feriado = "Finados"],
				    [Data = #date(2018,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2018,12,25), Feriado = "Natal"],
				    [Data = #date(2019,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2019,3,4), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2019,3,5), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2019,4,19), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2019,4,21), Feriado = "Páscoa"],
				    [Data = #date(2019,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2019,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2019,6,20), Feriado = "Corpus Christi"],
				    [Data = #date(2019,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2019,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2019,11,2), Feriado = "Finados"],
				    [Data = #date(2019,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2019,12,25), Feriado = "Natal"],
				    [Data = #date(2020,1,1), Feriado = "Confraternização Universal"],
				    [Data = #date(2020,2,24), Feriado = "Carnaval (Segunda-feira)"],
				    [Data = #date(2020,2,25), Feriado = "Carnaval (Terça-feira)"],
				    [Data = #date(2020,4,10), Feriado = "Sexta-feira Santa"],
				    [Data = #date(2020,4,12), Feriado = "Páscoa"],
				    [Data = #date(2020,4,21), Feriado = "Tiradentes"],
				    [Data = #date(2020,5,1), Feriado = "Dia do Trabalho"],
				    [Data = #date(2020,6,11), Feriado = "Corpus Christi"],
				    [Data = #date(2020,9,7), Feriado = "Independência do Brasil"],
				    [Data = #date(2020,10,12), Feriado = "Nossa Senhora Aparecida"],
				    [Data = #date(2020,11,2), Feriado = "Finados"],
				    [Data = #date(2020,11,15), Feriado = "Proclamação da República"],
				    [Data = #date(2020,12,25), Feriado = "Natal"]
				    }),
				    #"Feriados Tipados" = Table.TransformColumnTypes(Feriados, {{"Data", type date}}),
				    #"Feriados Agrupados" = Table.Group(#"Feriados Tipados", {"Data"}, {{"Feriado", each Text.Combine(List.Distinct([Feriado]), " / "), type text}}),
				
				    #"Mesclagem com Feriados" = Table.NestedJoin(#"Tipo Alterado", {"Date"}, #"Feriados Agrupados", {"Data"}, "FeriadosDetalhe", JoinKind.LeftOuter),
				    #"Feriado Expandido" = Table.ExpandTableColumn(#"Mesclagem com Feriados", "FeriadosDetalhe", {"Feriado"}, {"Nome Feriado"}),
				    #"É Feriado Adicionada" = Table.AddColumn(#"Feriado Expandido", "É Feriado", each [Nome Feriado] <> null, type logical),
				
				    #"Ano Adicionada" = Table.AddColumn(#"É Feriado Adicionada", "Ano", each Date.Year([Date]), Int64.Type),
				    #"MêsNúmero Adicionada" = Table.AddColumn(#"Ano Adicionada", "Mês Número", each Date.Month([Date]), Int64.Type),
				    #"Mês Adicionada" = Table.AddColumn(#"MêsNúmero Adicionada", "Mês", each Text.Proper(Date.ToText([Date], "MMMM", "pt-BR")), type text),
				    #"AnoMês Adicionada" = Table.AddColumn(#"Mês Adicionada", "Ano-Mês", each Date.ToText([Date], "yyyy-MM"), type text),
				    #"Trimestre Adicionada" = Table.AddColumn(#"AnoMês Adicionada", "Trimestre", each "T" & Number.ToText(Date.QuarterOfYear([Date])), type text),
				    #"AnoTrimestre Adicionada" = Table.AddColumn(#"Trimestre Adicionada", "Ano-Trimestre", each Number.ToText([Ano]) & "-" & [Trimestre], type text),
				    #"Dia Adicionada" = Table.AddColumn(#"AnoTrimestre Adicionada", "Dia", each Date.Day([Date]), Int64.Type),
				    #"DiaSemanaNúmero Adicionada" = Table.AddColumn(#"Dia Adicionada", "Dia Semana Número", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"DiaSemana Adicionada" = Table.AddColumn(#"DiaSemanaNúmero Adicionada", "Dia da Semana", each Text.Proper(Date.ToText([Date], "dddd", "pt-BR")), type text),
				    #"FimDeSemana Adicionada" = Table.AddColumn(#"DiaSemana Adicionada", "Fim de Semana", each [Dia Semana Número] >= 6, type logical),
				    #"InícioMês Adicionada" = Table.AddColumn(#"FimDeSemana Adicionada", "Início do Mês", each Date.StartOfMonth([Date]), type date),
				    #"FimMês Adicionada" = Table.AddColumn(#"InícioMês Adicionada", "Fim do Mês", each Date.EndOfMonth([Date]), type date),
				    #"SemanaAno Adicionada" = Table.AddColumn(#"FimMês Adicionada", "Semana do Ano", each Date.WeekOfYear([Date], Day.Monday), Int64.Type),
				    #"DiaDoAno Adicionada" = Table.AddColumn(#"SemanaAno Adicionada", "Dia do Ano", each Date.DayOfYear([Date]), Int64.Type)
				in
				    #"DiaDoAno Adicionada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

